# Generated by Django 4.2.5 on 2023-10-23 06:44

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'ordering': ['parent_category', 'sub_category_name'], 'verbose_name': 'Sub Category', 'verbose_name_plural': 'Sub Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='category_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='category/', verbose_name='Category Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Product_Image PPOI'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='category/', verbose_name='Product_Image'),
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant_name', models.CharField(max_length=150)),
                ('variant_description', models.TextField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_variants', to='products.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', versatileimagefield.fields.VersatileImageField(upload_to='category/', verbose_name='Product_Image')),
                ('ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20, verbose_name='Product_Image PPOI')),
                ('product_varient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='product_images', to='products.productvariant')),
            ],
        ),
    ]
