# Generated by Django 4.2.5 on 2023-10-23 06:50

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_category_options_alter_subcategory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='category_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='category/', verbose_name='Category Image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=versatileimagefield.fields.VersatileImageField(default=1, upload_to='category/', verbose_name='Product_Image'),
            preserve_default=False,
        ),
    ]
